# Site configuration
title: MCQ Online
description: Online tool for practicing your MCQ exams
keywords: Epidocs, MCQ, online, practicing, exams, EPITA
author: Matiboux
lang: en

# Jekyll confiuration
exclude: [CNAME]
